name: Fedora Rawhide

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: fedora:rawhide
      options: --security-opt seccomp=unconfined
      volumes:
        - ${{ github.workspace }}:/w

    steps:
      - uses: actions/checkout@v2

      - name: Update system
        run: dnf -y update
        
      - name: Install nvm
        shell: bash -l {0}
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          echo "source $NVM_DIR/nvm.sh --install" >> "$HOME/.bash_profile"
          $NVM_DIR/nvm.sh install 17
      
      - run: node -v
      
      - run: corepack enable
    
      - run: yarn install --frozen-lockfile
      
      - run: yarn build
