name: Fedora Rawhide

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: fedora:rawhide
      options: --security-opt seccomp=unconfined
      volumes:
        - ${{ github.workspace }}:/w

    steps:
      - uses: actions/checkout@v2

      - name: Update system
        run: dnf -y update
        
      - run: curl -fsSL https://rpm.nodesource.com/setup_17.x | sudo bash -
      
      - run: dnf install -y nodejs
      
      - run: corepack enable
    
      - run: yarn install --frozen-lockfile
      
      - run: yarn build
